#!/usr/bin/env python
"""
Run `syncstream-remote --help` for more info

Created on Tue May 24 20:43 2022

@author: MaxWinsemius
"""

import argparse
from src.remote import commands

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description = "SyncStream Remote - the cli tool for your SyncStream Daemon!",
    )

    subparsers = parser.add_subparsers()

    for command in commands.all:
        command.add_parser_subcommand(subparsers)

    args = parser.parse_args()

    from pprint import pprint
    pprint(args)

    print("exiting")
